import type { Metadata, Viewport } from 'next';
import './globals.css';
import { structuredData } from './utils/seo';

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  // Browser bar colour. Phones: black, to match the always-dark mobile header.
  // Larger screens: the entry without a media query, kept in sync with the
  // site theme toggle by the pre-paint script below and by useTheme.
  themeColor: [
    { media: '(max-width: 767px)', color: '#09090b' },
    { color: '#ffffff' }
  ]
};

export const metadata: Metadata = {
  metadataBase: new URL('https://tech.omni-solutions.co'),
  title: {
    default: 'Omni Tech Solutions — софтуерни решения, мрежи и ИТ услуги',
    template: '%s | Omni Tech Solutions'
  },
  description: 'Софтуер по поръчка и изграждане на мрежи, както и уебсайтове, компютърна поддръжка и видеонаблюдение за дома и бизнеса в България. Безплатна консултация.',
  keywords: [
    'софтуер по поръчка България',
    'изграждане на мрежи',
    'Wi-Fi покритие',
    'ИТ услуги',
    'изработка на сайт',
    'видеонаблюдение',
    'монтаж на камери',
    'IP камери',
    'компютърен сервиз',
    'инсталация на Windows',
    'ИТ поддръжка',
    'IT services Bulgaria',
    'CCTV installation Bulgaria'
  ],
  authors: [{ name: 'Omni Tech Solutions' }],
  creator: 'Omni Tech Solutions',
  publisher: 'Omni Tech Solutions',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  // One URL per page: the language switch happens in the browser, so there are
  // no /en or /tr pages to point search engines at.
  alternates: {
    canonical: '/',
  },
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
      { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
    ],
    apple: [{ url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' }],
  },
  manifest: '/site.webmanifest',
  openGraph: {
    type: 'website',
    locale: 'bg_BG',
    alternateLocale: ['en_US', 'tr_TR'],
    url: 'https://tech.omni-solutions.co',
    siteName: 'Omni Tech Solutions',
    title: 'Omni Tech Solutions — софтуер, мрежи и ИТ услуги',
    description: 'Софтуер по поръчка и мрежи, както и уебсайтове, компютърна поддръжка и видеонаблюдение за дома и бизнеса.',
    // PNG, not SVG — WhatsApp, Messenger and Viber don't show SVG previews.
    // Generated by scripts/og/generate.mjs.
    images: [
      {
        url: '/og/home.png',
        width: 1200,
        height: 630,
        type: 'image/png',
        alt: 'Omni Tech Solutions — софтуерни решения и ИТ инфраструктура за бизнеса',
      }
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Omni Tech Solutions — софтуер, мрежи и ИТ услуги',
    description: 'Софтуер по поръчка и мрежи, както и уебсайтове, компютърна поддръжка и видеонаблюдение за дома и бизнеса.',
    images: ['/og/home.png'],
  },
  // Site ownership for the webmaster tools, set at build time. Values missing
  // from the environment are simply left out of the page.
  verification: {
    google: process.env.GOOGLE_SITE_VERIFICATION,
    yandex: process.env.YANDEX_SITE_VERIFICATION,
    other: process.env.BING_SITE_VERIFICATION
      ? { 'msvalidate.01': process.env.BING_SITE_VERIFICATION }
      : undefined,
  },
  category: 'technology',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // suppressHydrationWarning: the pre-paint script adds the theme class before React loads
    <html lang="bg" suppressHydrationWarning>
      <head>
        {/*
          Apply the saved theme before the first paint, so the page canvas and the
          browser bar never flash white for visitors who chose the dark theme.
        */}
        <script
          dangerouslySetInnerHTML={{
            __html: "try{var t=localStorage.getItem('theme')==='dark'?'dark':'light';document.documentElement.classList.add(t);if(t==='dark'){var m=document.querySelector('meta[name=\"theme-color\"]:not([media])');if(m)m.setAttribute('content','#18181b')}}catch(e){}"
          }}
        />
        {/* Structured Data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(structuredData.organization)
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(structuredData.localBusiness)
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(structuredData.website)
          }}
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
