import type { Metadata } from 'next';
import { SERVICE_IDS } from '@/app/config/services';

const BASE_URL = 'https://tech.omni-solutions.co';

/**
 * Per-service metadata. Bulgarian is the primary language of the site, so the
 * meta copy is Bulgarian with the key terms spelled out.
 */
const SERVICE_SEO: Record<string, { title: string; description: string; keywords: string[] }> = {
    'video-surveillance': {
        title: 'Видеонаблюдение и монтаж на камери',
        description:
            'Монтаж на камери и системи за видеонаблюдение с отдалечен достъп за дома и бизнеса. Ясни цени за монтаж, настройка и профилактика.',
        keywords: ['видеонаблюдение', 'монтаж на камери', 'IP камери', 'охранителни камери', 'цена монтаж на камера'],
    },
    'local-networks': {
        title: 'Изграждане на мрежи и Wi-Fi',
        description:
            'Локални мрежи, окабеляване и професионално Wi-Fi покритие за дома, офиса и обекта.',
        keywords: ['изграждане на мрежа', 'Wi-Fi покритие', 'настройка на рутер', 'LAN окабеляване'],
    },
    'operating-systems': {
        title: 'Инсталация на Windows и компютърен сервиз',
        description:
            'Преинсталация на Windows, смяна на SSD, почистване и премахване на вируси, със запазване на данните.',
        keywords: ['инсталация на Windows', 'компютърен сервиз', 'смяна на SSD', 'почистване на лаптоп'],
    },
    'web-design': {
        title: 'Информационни сайтове и онлайн магазини',
        description:
            'Бързи и адаптивни уебсайтове и онлайн магазини, оптимизирани за търсачки и за продажби. Работим с клиенти в България и чужбина.',
        keywords: ['изработка на сайт България', 'онлайн магазин изработка', 'уеб дизайн', 'сайт за бизнес'],
    },
    'maintenance-support': {
        title: 'Абонамент за ИТ поддръжка',
        description:
            'Месечни проверки, актуализации и дистанционна помощ за вече изградени системи за видеонаблюдение, мрежи и компютри.',
        keywords: ['ИТ поддръжка', 'абонамент поддръжка', 'поддръжка на уебсайт', 'сервиз на видеонаблюдение'],
    },
    'network-security-audit': {
        title: 'Одит на мрежовата сигурност за малък бизнес',
        description:
            'Проверка на мрежата, рутера и системата за видеонаблюдение на малкия бизнес, с ясен доклад какво да се поправи първо.',
        keywords: ['мрежова сигурност', 'одит на мрежа малък бизнес', 'сигурност на камери'],
    },
    'web-applications': {
        title: 'Уеб, настолни и мобилни приложения по поръчка',
        description:
            'Софтуер по поръчка за браузър, десктоп и телефон, с интеграции и автоматизация на бизнес процеси. Клиенти в България и чужбина.',
        keywords: ['софтуер по поръчка България', 'уеб приложение по поръчка', 'разработка на настолно приложение', 'десктоп приложение по поръчка', 'разработка на мобилно приложение', 'автоматизация на бизнес процеси'],
    },
};

export async function generateStaticParams() {
    return SERVICE_IDS.map((serviceId) => ({ serviceId }));
}

export async function generateMetadata({
    params,
}: {
    // Next 15: route params arrive as a Promise
    params: Promise<{ serviceId: string }>;
}): Promise<Metadata> {
    const { serviceId } = await params;
    const seo = SERVICE_SEO[serviceId];

    if (!seo) {
        return { title: 'Услуги' };
    }

    const url = `${BASE_URL}/services/${serviceId}`;
    // The root layout's title template adds "| Omni Tech Solutions" to the page
    // title; share previews don't use the template, so the brand is added here.
    const shareTitle = `${seo.title} | Omni Tech Solutions`;
    // Per-service preview image, generated by scripts/og/generate.mjs
    const image = {
        url: `/og/${serviceId}.png`,
        width: 1200,
        height: 630,
        type: 'image/png',
        alt: seo.title,
    };

    return {
        title: seo.title,
        description: seo.description,
        keywords: seo.keywords,
        alternates: { canonical: url },
        openGraph: {
            type: 'website',
            url,
            title: shareTitle,
            description: seo.description,
            siteName: 'Omni Tech Solutions',
            locale: 'bg_BG',
            images: [image],
        },
        twitter: {
            card: 'summary_large_image',
            title: shareTitle,
            description: seo.description,
            images: [image.url],
        },
    };
}

export default function ServiceLayout({ children }: { children: React.ReactNode }) {
    return <>{children}</>;
}
